language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm run lint
script:
  - npm start
before_deploy:
  - cp README.md build/
deploy:
  - provider: script
    script: npm run deploy
    on:
      branch: master
      # https://github.com/travis-ci/travis-conditions/issues/16
      # condition: $USERNAME IS present && $PASSWORD IS present
      condition: $USERNAME && $PASSWORD
  - provider: pages
    github_token: $GITHUB_TOKEN
    skip-cleanup: true
    keep-history: false
    local-dir: build
    on:
      branch: master
      # condition: $GITHUB_TOKEN IS present
      condition: $GITHUB_TOKEN
